FILLING_ERROR_FLAG = 1
PARSING_ERROR_FLAG = 2
EXECUTION_ERROR_FLAG = 3
ERROR_FLAGS = {
    FILLING_ERROR_FLAG: "Filling Error",
    PARSING_ERROR_FLAG: "Parsing Error",
    EXECUTION_ERROR_FLAG: "Execution Error"
}